/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./../components/avatar/index.vue')['default']
    CustomCascader: typeof import('./../components/Custom/CustomCascader/index.vue')['default']
    CustomDatePicker: typeof import('./../components/Custom/CustomDatePicker/index.vue')['default']
    CustomIconInput: typeof import('./../components/Custom/CustomIconInput/index.vue')['default']
    CustomPagination: typeof import('./../components/Custom/CustomPagination/index.vue')['default']
    CustomSearch: typeof import('./../components/Custom/CustomSearch/index.vue')['default']
    CustomTable: typeof import('./../components/Custom/CustomTable/index.vue')['default']
    CustomTag: typeof import('./../components/Custom/CustomTag/index.vue')['default']
    CustomTreeSelect: typeof import('./../components/Custom/CustomTreeSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Upload: typeof import('./../components/Upload/index.vue')['default']
  }
}
